services:
  - type: web
    name: grad-app
    env: static
    buildCommand: npm run build
    staticPublishPath: ./build
    routes:
      - src: /.*
        dest: /index.html
        action: rewrite